### ISSUE TITLE
Mappleton's "Leyendecker" >> Sync status box renders empty

### ISSUE THREAD

**Issue by XVVH** [theianjones/roam-research-themes#13]
A while back the Roam team introduced a detailed sync status when you mouse over the green/amber sync status indicator at the top of your DB. When Maggie Appleton's "_Leyendecker_" is enabled, this tool tip/pop-over is now showing as blank. 

Disabling the theme allows the tool top to be rendered properly - see attached screenshots

With the standard Roam theme, showing the status box: (_Leyendecker_ disabled by changing the code block from CSS to Clojure)
<img width="1153" alt="capture 128" src="https://user-images.githubusercontent.com/65286726/89114862-f15a8380-d44e-11ea-9fcb-2efe615e2ee6.png">

With _Leyendecker_, showing that the status box is rendering empty:
<img width="1115" alt="capture 129" src="https://user-images.githubusercontent.com/65286726/89114883-1818ba00-d44f-11ea-8f55-993091aa9fe3.png">

**Comment by iff** [comment]
I think the issue is just that the font color (`color: var(--text-color);`) is very similar to the background color (not themed at the moment). One possible hack would be to change the background color of the status box:

```
.bp3-popover-content {
    background-color: var(--bg-color) !important;
    color: var(--text-color) !important;
}
```

**Comment by MaggieAppleton** [comment]
@iff Thanks for the suggestion in fixing this. Just updated the theme with it: https://github.com/theianjones/roam-research-themes/commit/e8dc5f8271ad603504970b855b4478d6bf7dad48
