### ISSUE TITLE
The "All Pages" view is not nicely catered for in the dark theme

### ISSUE THREAD

**Issue by ybalkind** [theianjones/roam-research-themes#5]
![image](https://user-images.githubusercontent.com/10196054/80720775-b0746b00-8afd-11ea-9a1c-e10e3a43380d.png)

relates to https://roamresearch.com/#/app/nameofdb/search

**Comment by isaacplmann** [comment]
I added this rule:

```
/* rows */
.rm-pages-row:first-of-type,
.rm-pages-row-highlight {
    background-color: #2e3250 !important;
}
```

And modified this one:
```
a {
  color: #64b5f6 !important;
}
```

Now the All Pages view looks like this:
![Screen Shot 2020-05-25 at 10 08 37 AM](https://user-images.githubusercontent.com/861504/82820183-b72d9e00-9e6f-11ea-854a-b5881f8511a7.png)

**Comment by theianjones** [comment]
Awesome @isaacplmann could you pr these changes? that looks great
